"""add_chat_messages_composite_index

Revision ID: 66939b9f8def
Revises: be9084238547
Create Date: 2026-02-09 20:38:43.229674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66939b9f8def'
down_revision: Union[str, Sequence[str], None] = 'be9084238547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_session_created', table_name='chat_messages')
    # ### end Alembic commands ###
