"""add_job_categorization_fields_v2

Revision ID: 8984c2bfa7af
Revises: 007_candidate_module
Create Date: 2026-02-06 22:34:57.622845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8984c2bfa7af'
down_revision: Union[str, Sequence[str], None] = '007_candidate_module'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='Message text content',
               existing_comment='Message text',
               existing_nullable=False)
    op.alter_column('candidate_chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type: text, buttons, select, multi_select, boolean, etc.',
               existing_comment='text, buttons, select, etc.',
               existing_nullable=False)
    op.alter_column('candidate_chat_messages', 'message_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional data (options, validation rules, etc.)',
               existing_comment='Additional data',
               existing_nullable=True)
    op.drop_index(op.f('idx_candidate_chat_messages_created_at'), table_name='candidate_chat_messages')
    op.drop_index(op.f('idx_candidate_chat_messages_session_id'), table_name='candidate_chat_messages')
    op.alter_column('candidate_chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Session title (auto-generated)',
               existing_comment='Session title',
               existing_nullable=True)
    op.alter_column('candidate_chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type: resume_creation, resume_upload, general',
               existing_comment='resume_creation, resume_upload, general',
               existing_nullable=False)
    op.alter_column('candidate_chat_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: active, completed, abandoned',
               existing_comment='active, completed, abandoned',
               existing_nullable=False)
    op.alter_column('candidate_chat_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Session context (collected_data, step, resume_id, etc.)',
               existing_comment='Session context (collected_data, step, etc.)',
               existing_nullable=True)
    op.alter_column('candidate_chat_sessions', 'resume_id',
               existing_type=sa.UUID(),
               comment='FK to created resume',
               existing_nullable=True)
    op.drop_index(op.f('idx_candidate_chat_sessions_candidate_id'), table_name='candidate_chat_sessions')
    op.alter_column('candidate_resumes', 'resume_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured resume data (JSON) for job matching',
               existing_comment='Structured resume data',
               existing_nullable=True)
    op.alter_column('candidate_resumes', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to resume PDF in S3/Supabase',
               existing_comment='Resume PDF URL',
               existing_nullable=True)
    op.alter_column('candidate_resumes', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='How resume was created: aivi_bot, pdf_upload',
               existing_comment='aivi_bot or pdf_upload',
               existing_nullable=False)
    op.alter_column('candidate_resumes', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: in_progress, completed, invalidated',
               existing_comment='in_progress, completed, invalidated',
               existing_nullable=False)
    op.alter_column('candidate_resumes', 'chat_session_id',
               existing_type=sa.UUID(),
               comment='FK to candidate_chat_sessions (if created via bot)',
               existing_comment='FK to chat session',
               existing_nullable=True)
    op.alter_column('candidates', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary mobile number (source of truth, immutable)',
               existing_comment='Primary mobile (source of truth)',
               existing_nullable=False)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Candidate's full name",
               existing_comment='Full name',
               existing_nullable=False)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address (optional)',
               existing_comment='Email (optional)',
               existing_nullable=True)
    op.alter_column('candidates', 'profile_photo_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to profile photo in S3/Supabase Storage',
               existing_comment='Profile photo URL',
               existing_nullable=True)
    op.alter_column('candidates', 'preferred_job_category_id',
               existing_type=sa.UUID(),
               comment='Preferred job category',
               existing_nullable=True)
    op.alter_column('candidates', 'preferred_job_role_id',
               existing_type=sa.UUID(),
               comment='Preferred job role',
               existing_nullable=True)
    op.alter_column('candidates', 'languages_known',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Languages known (JSON array of strings)',
               existing_comment='Languages (JSON array)',
               existing_nullable=True)
    op.alter_column('candidates', 'about',
               existing_type=sa.TEXT(),
               comment='Short bio / about the candidate',
               existing_comment='Short bio',
               existing_nullable=True)
    op.alter_column('candidates', 'current_monthly_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Current monthly salary in INR',
               existing_comment='Current salary INR',
               existing_nullable=True)
    op.alter_column('candidates', 'aadhaar_number_encrypted',
               existing_type=sa.VARCHAR(length=500),
               comment='Encrypted Aadhaar number',
               existing_comment='Encrypted Aadhaar',
               existing_nullable=True)
    op.alter_column('candidates', 'pan_number_encrypted',
               existing_type=sa.VARCHAR(length=500),
               comment='Encrypted PAN number',
               existing_comment='Encrypted PAN',
               existing_nullable=True)
    op.alter_column('candidates', 'profile_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Profile status: basic, complete',
               existing_comment='basic or complete',
               existing_nullable=False)
    op.alter_column('candidates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Message role: bot or user',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='Message text content',
               existing_nullable=False)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Type: text, buttons, job_preview, etc.',
               existing_nullable=False)
    op.alter_column('chat_messages', 'message_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional data (button options, job data, etc.)',
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Session title (auto-generated from context)',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Type: job_creation, general, etc.',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Session context (e.g., job_id if created, collected_data)',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_chat_sessions_created_at'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_employer_id'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_is_active'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_employer_active', 'chat_sessions', ['employer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_chat_sessions_employer_id'), 'chat_sessions', ['employer_id'], unique=False)
    op.alter_column('employers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Contact person's full name",
               existing_nullable=False)
    op.alter_column('employers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary email address',
               existing_nullable=False)
    op.alter_column('employers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment='Phone number with country code',
               existing_nullable=True)
    op.alter_column('employers', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company/organization name',
               existing_nullable=False)
    op.alter_column('employers', 'company_description',
               existing_type=sa.TEXT(),
               comment='About the company',
               existing_nullable=True)
    op.alter_column('employers', 'company_website',
               existing_type=sa.VARCHAR(length=500),
               comment='Company website URL',
               existing_nullable=True)
    op.alter_column('employers', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment='Company size: startup, small, medium, large, enterprise',
               existing_nullable=True)
    op.alter_column('employers', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment='Industry/sector',
               existing_nullable=True)
    op.alter_column('employers', 'headquarters_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Main office location',
               existing_nullable=True)
    op.alter_column('employers', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_nullable=True)
    op.alter_column('employers', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment='State/Province',
               existing_nullable=True)
    op.alter_column('employers', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='Country',
               existing_nullable=True)
    op.alter_column('employers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether employer is verified',
               existing_nullable=False)
    op.alter_column('employers', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When verification happened',
               existing_nullable=True)
    op.alter_column('employers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employers', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_employers_company_name'), table_name='employers')
    op.drop_index(op.f('ix_employers_created_at'), table_name='employers')
    op.drop_index(op.f('ix_employers_email'), table_name='employers')
    op.drop_index(op.f('ix_employers_is_active'), table_name='employers')
    op.alter_column('extractions', 'employer_id',
               existing_type=sa.UUID(),
               comment='Reference to employer (if known)',
               existing_nullable=True)
    op.alter_column('extractions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Idempotency key for this extraction',
               existing_nullable=True)
    op.alter_column('extractions', 'raw_jd',
               existing_type=sa.TEXT(),
               comment='Original job description text',
               existing_nullable=False)
    op.alter_column('extractions', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Extracted fields as JSON',
               existing_nullable=True)
    op.alter_column('extractions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Status: pending, processing, completed, failed',
               existing_nullable=False)
    op.alter_column('extractions', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('extractions', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Number of processing attempts',
               existing_nullable=False)
    op.alter_column('extractions', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When extraction was processed',
               existing_nullable=True)
    op.drop_index(op.f('ix_extractions_created_at'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_employer_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_idempotency_key'), table_name='extractions')
    op.create_index('idx_extractions_created_at', 'extractions', ['created_at'], unique=False)
    op.create_index('idx_extractions_employer_id', 'extractions', ['employer_id'], unique=False)
    op.create_index('idx_extractions_idempotency_key', 'extractions', ['idempotency_key'], unique=False)
    op.create_index('idx_extractions_status', 'extractions', ['status'], unique=False)
    op.drop_constraint(op.f('fk_extractions_employer_id'), 'extractions', type_='foreignkey')
    op.create_foreign_key(None, 'extractions', 'employers', ['employer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('job_categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Category name (e.g., Technology, Delivery & Logistics)',
               existing_comment='Category name',
               existing_nullable=False)
    op.alter_column('job_categories', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment='Icon name/class for frontend',
               existing_comment='Icon name for frontend',
               existing_nullable=True)
    op.alter_column('job_categories', 'display_order',
               existing_type=sa.INTEGER(),
               comment='Order for UI display (lower = first)',
               existing_comment='Display order',
               existing_nullable=False)
    op.drop_index(op.f('idx_job_categories_display_order'), table_name='job_categories')
    op.drop_index(op.f('idx_job_categories_is_active'), table_name='job_categories')
    op.drop_index(op.f('idx_job_categories_slug'), table_name='job_categories')
    op.drop_index(op.f('idx_category_role_category'), table_name='job_category_role_association')
    op.drop_index(op.f('idx_category_role_role'), table_name='job_category_role_association')
    op.alter_column('job_roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Role name (e.g., Software Developer, Delivery Boy)',
               existing_comment='Role name',
               existing_nullable=False)
    op.alter_column('job_roles', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Job type: blue_collar or white_collar',
               existing_comment='blue_collar or white_collar',
               existing_nullable=False)
    op.alter_column('job_roles', 'suggested_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Suggested skill tags for this role (JSON array)',
               existing_comment='Suggested skill tags',
               existing_nullable=True)
    op.drop_index(op.f('idx_job_roles_is_active'), table_name='job_roles')
    op.drop_index(op.f('idx_job_roles_job_type'), table_name='job_roles')
    op.drop_index(op.f('idx_job_roles_slug'), table_name='job_roles')
    op.add_column('jobs', sa.Column('category_id', sa.UUID(), nullable=True, comment='Reference to job category'))
    op.add_column('jobs', sa.Column('role_id', sa.UUID(), nullable=True, comment='Reference to specific job role'))
    op.alter_column('jobs', 'employer_id',
               existing_type=sa.UUID(),
               comment='Reference to employer who created this job',
               existing_nullable=False)
    op.alter_column('jobs', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Idempotency key to prevent duplicate job creation',
               existing_nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Job title',
               existing_nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               comment='Full job description (original JD)',
               existing_nullable=False)
    op.alter_column('jobs', 'requirements',
               existing_type=sa.TEXT(),
               comment='Job requirements (extracted or manual)',
               existing_nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment="Location string (e.g., 'San Francisco, CA')",
               existing_nullable=True)
    op.alter_column('jobs', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City name',
               existing_nullable=True)
    op.alter_column('jobs', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment='State/Province',
               existing_nullable=True)
    op.alter_column('jobs', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='Country',
               existing_nullable=True)
    op.alter_column('jobs', 'work_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Work type: remote, hybrid, onsite',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_range_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               comment='Minimum salary',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_range_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               comment='Maximum salary',
               existing_nullable=True)
    op.alter_column('jobs', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_comment='Salary currency: INR, USD, etc.',
               existing_nullable=True)
    op.alter_column('jobs', 'shift_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Shift preferences as JSON',
               existing_nullable=True)
    op.alter_column('jobs', 'openings_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Number of positions available',
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Job status: draft, published, paused, closed',
               existing_nullable=False)
    op.alter_column('jobs', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When job was first published',
               existing_nullable=True)
    op.alter_column('jobs', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When job was closed',
               existing_nullable=True)
    op.alter_column('jobs', 'close_reason',
               existing_type=sa.VARCHAR(length=255),
               comment='Reason for closing the job',
               existing_nullable=True)
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employer_status_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_work_type'), table_name='jobs')
    op.create_index('idx_jobs_city_state', 'jobs', ['city', 'state'], unique=False)
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_employer_id', 'jobs', ['employer_id'], unique=False)
    op.create_index('idx_jobs_idempotency_key', 'jobs', ['idempotency_key'], unique=False)
    op.create_index('idx_jobs_is_active_status', 'jobs', ['is_active', 'status'], unique=False)
    op.create_index('idx_jobs_published_at', 'jobs', ['published_at'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_jobs_work_type', 'jobs', ['work_type'], unique=False)
    op.create_index(op.f('ix_jobs_category_id'), 'jobs', ['category_id'], unique=False)
    op.create_index(op.f('ix_jobs_role_id'), 'jobs', ['role_id'], unique=False)
    op.drop_constraint(op.f('fk_jobs_employer_id'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'job_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'job_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'employers', ['employer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('role_question_templates', 'question_key',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique key for this question (e.g., has_driving_license)',
               existing_comment='Unique key for this question',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'question_text',
               existing_type=sa.TEXT(),
               comment='Question text displayed to candidate',
               existing_comment='Question text',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Input type: text, boolean, select, multi_select, number, date, file',
               existing_comment='Input type',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Options for select/multi_select (JSON array)',
               existing_comment='Options for select/multi_select',
               existing_nullable=True)
    op.alter_column('role_question_templates', 'is_required',
               existing_type=sa.BOOLEAN(),
               comment='Whether this question must be answered',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'display_order',
               existing_type=sa.INTEGER(),
               comment='Order in the questioning flow',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'condition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Conditional display rule (JSON)',
               existing_comment='Conditional display rule',
               existing_nullable=True)
    op.alter_column('role_question_templates', 'validation_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Validation rules (JSON)',
               existing_comment='Validation rules',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_question_templates', 'validation_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Validation rules',
               existing_comment='Validation rules (JSON)',
               existing_nullable=True)
    op.alter_column('role_question_templates', 'condition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Conditional display rule',
               existing_comment='Conditional display rule (JSON)',
               existing_nullable=True)
    op.alter_column('role_question_templates', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Order in the questioning flow',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'is_required',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this question must be answered',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Options for select/multi_select',
               existing_comment='Options for select/multi_select (JSON array)',
               existing_nullable=True)
    op.alter_column('role_question_templates', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Input type',
               existing_comment='Input type: text, boolean, select, multi_select, number, date, file',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'question_text',
               existing_type=sa.TEXT(),
               comment='Question text',
               existing_comment='Question text displayed to candidate',
               existing_nullable=False)
    op.alter_column('role_question_templates', 'question_key',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique key for this question',
               existing_comment='Unique key for this question (e.g., has_driving_license)',
               existing_nullable=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_jobs_employer_id'), 'jobs', 'employers', ['employer_id'], ['id'])
    op.drop_index(op.f('ix_jobs_role_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_category_id'), table_name='jobs')
    op.drop_index('idx_jobs_work_type', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_published_at', table_name='jobs')
    op.drop_index('idx_jobs_is_active_status', table_name='jobs')
    op.drop_index('idx_jobs_idempotency_key', table_name='jobs')
    op.drop_index('idx_jobs_employer_id', table_name='jobs')
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.drop_index('idx_jobs_city_state', table_name='jobs')
    op.create_index(op.f('ix_jobs_work_type'), 'jobs', ['work_type'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_jobs_employer_status_active'), 'jobs', ['employer_id', 'status', 'is_active'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.alter_column('jobs', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('jobs', 'close_reason',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reason for closing the job',
               existing_nullable=True)
    op.alter_column('jobs', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When job was closed',
               existing_nullable=True)
    op.alter_column('jobs', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When job was first published',
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'''draft'''::character varying"),
               comment=None,
               existing_comment='Job status: draft, published, paused, closed',
               existing_nullable=False)
    op.alter_column('jobs', 'openings_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='Number of positions available',
               existing_nullable=False)
    op.alter_column('jobs', 'shift_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Shift preferences as JSON',
               existing_nullable=True)
    op.alter_column('jobs', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'INR'::character varying"),
               existing_comment='Salary currency: INR, USD, etc.',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_range_max',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Maximum salary',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_range_min',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Minimum salary',
               existing_nullable=True)
    op.alter_column('jobs', 'work_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Work type: remote, hybrid, onsite',
               existing_nullable=True)
    op.alter_column('jobs', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Country',
               existing_nullable=True)
    op.alter_column('jobs', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='State/Province',
               existing_nullable=True)
    op.alter_column('jobs', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City name',
               existing_nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Location string (e.g., 'San Francisco, CA')",
               existing_nullable=True)
    op.alter_column('jobs', 'requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Job requirements (extracted or manual)',
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full job description (original JD)',
               existing_nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Job title',
               existing_nullable=False)
    op.alter_column('jobs', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Idempotency key to prevent duplicate job creation',
               existing_nullable=True)
    op.alter_column('jobs', 'employer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to employer who created this job',
               existing_nullable=False)
    op.drop_column('jobs', 'role_id')
    op.drop_column('jobs', 'category_id')
    op.create_index(op.f('idx_job_roles_slug'), 'job_roles', ['slug'], unique=False)
    op.create_index(op.f('idx_job_roles_job_type'), 'job_roles', ['job_type'], unique=False)
    op.create_index(op.f('idx_job_roles_is_active'), 'job_roles', ['is_active'], unique=False)
    op.alter_column('job_roles', 'suggested_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Suggested skill tags',
               existing_comment='Suggested skill tags for this role (JSON array)',
               existing_nullable=True)
    op.alter_column('job_roles', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment='blue_collar or white_collar',
               existing_comment='Job type: blue_collar or white_collar',
               existing_nullable=False)
    op.alter_column('job_roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Role name',
               existing_comment='Role name (e.g., Software Developer, Delivery Boy)',
               existing_nullable=False)
    op.create_index(op.f('idx_category_role_role'), 'job_category_role_association', ['role_id'], unique=False)
    op.create_index(op.f('idx_category_role_category'), 'job_category_role_association', ['category_id'], unique=False)
    op.create_index(op.f('idx_job_categories_slug'), 'job_categories', ['slug'], unique=False)
    op.create_index(op.f('idx_job_categories_is_active'), 'job_categories', ['is_active'], unique=False)
    op.create_index(op.f('idx_job_categories_display_order'), 'job_categories', ['display_order'], unique=False)
    op.alter_column('job_categories', 'display_order',
               existing_type=sa.INTEGER(),
               comment='Display order',
               existing_comment='Order for UI display (lower = first)',
               existing_nullable=False)
    op.alter_column('job_categories', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment='Icon name for frontend',
               existing_comment='Icon name/class for frontend',
               existing_nullable=True)
    op.alter_column('job_categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Category name',
               existing_comment='Category name (e.g., Technology, Delivery & Logistics)',
               existing_nullable=False)
    op.drop_constraint(None, 'extractions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_extractions_employer_id'), 'extractions', 'employers', ['employer_id'], ['id'])
    op.drop_index('idx_extractions_status', table_name='extractions')
    op.drop_index('idx_extractions_idempotency_key', table_name='extractions')
    op.drop_index('idx_extractions_employer_id', table_name='extractions')
    op.drop_index('idx_extractions_created_at', table_name='extractions')
    op.create_index(op.f('ix_extractions_idempotency_key'), 'extractions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_extractions_employer_id'), 'extractions', ['employer_id'], unique=False)
    op.create_index(op.f('ix_extractions_created_at'), 'extractions', ['created_at'], unique=False)
    op.alter_column('extractions', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When extraction was processed',
               existing_nullable=True)
    op.alter_column('extractions', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Number of processing attempts',
               existing_nullable=False)
    op.alter_column('extractions', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('extractions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'''pending'''::character varying"),
               comment=None,
               existing_comment='Status: pending, processing, completed, failed',
               existing_nullable=False)
    op.alter_column('extractions', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Extracted fields as JSON',
               existing_nullable=True)
    op.alter_column('extractions', 'raw_jd',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original job description text',
               existing_nullable=False)
    op.alter_column('extractions', 'idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Idempotency key for this extraction',
               existing_nullable=True)
    op.alter_column('extractions', 'employer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to employer (if known)',
               existing_nullable=True)
    op.create_index(op.f('ix_employers_is_active'), 'employers', ['is_active'], unique=False)
    op.create_index(op.f('ix_employers_email'), 'employers', ['email'], unique=True)
    op.create_index(op.f('ix_employers_created_at'), 'employers', ['created_at'], unique=False)
    op.create_index(op.f('ix_employers_company_name'), 'employers', ['company_name'], unique=False)
    op.alter_column('employers', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('employers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('employers', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When verification happened',
               existing_nullable=True)
    op.alter_column('employers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether employer is verified',
               existing_nullable=False)
    op.alter_column('employers', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Country',
               existing_nullable=True)
    op.alter_column('employers', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='State/Province',
               existing_nullable=True)
    op.alter_column('employers', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City',
               existing_nullable=True)
    op.alter_column('employers', 'headquarters_location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Main office location',
               existing_nullable=True)
    op.alter_column('employers', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Industry/sector',
               existing_nullable=True)
    op.alter_column('employers', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Company size: startup, small, medium, large, enterprise',
               existing_nullable=True)
    op.alter_column('employers', 'company_website',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Company website URL',
               existing_nullable=True)
    op.alter_column('employers', 'company_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='About the company',
               existing_nullable=True)
    op.alter_column('employers', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Company/organization name',
               existing_nullable=False)
    op.alter_column('employers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Phone number with country code',
               existing_nullable=True)
    op.alter_column('employers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Primary email address',
               existing_nullable=False)
    op.alter_column('employers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Contact person's full name",
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_sessions_employer_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_employer_active', table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_is_active'), 'chat_sessions', ['is_active'], unique=False)
    op.create_index(op.f('idx_chat_sessions_employer_id'), 'chat_sessions', ['employer_id'], unique=False)
    op.create_index(op.f('idx_chat_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False)
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Session context (e.g., job_id if created, collected_data)',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'job_creation'::character varying"),
               comment=None,
               existing_comment='Type: job_creation, general, etc.',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Session title (auto-generated from context)',
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.alter_column('chat_messages', 'message_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional data (button options, job data, etc.)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'text'::character varying"),
               comment=None,
               existing_comment='Type: text, buttons, job_preview, etc.',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Message text content',
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Message role: bot or user',
               existing_nullable=False)
    op.alter_column('candidates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('candidates', 'profile_status',
               existing_type=sa.VARCHAR(length=50),
               comment='basic or complete',
               existing_comment='Profile status: basic, complete',
               existing_nullable=False)
    op.alter_column('candidates', 'pan_number_encrypted',
               existing_type=sa.VARCHAR(length=500),
               comment='Encrypted PAN',
               existing_comment='Encrypted PAN number',
               existing_nullable=True)
    op.alter_column('candidates', 'aadhaar_number_encrypted',
               existing_type=sa.VARCHAR(length=500),
               comment='Encrypted Aadhaar',
               existing_comment='Encrypted Aadhaar number',
               existing_nullable=True)
    op.alter_column('candidates', 'current_monthly_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Current salary INR',
               existing_comment='Current monthly salary in INR',
               existing_nullable=True)
    op.alter_column('candidates', 'about',
               existing_type=sa.TEXT(),
               comment='Short bio',
               existing_comment='Short bio / about the candidate',
               existing_nullable=True)
    op.alter_column('candidates', 'languages_known',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Languages (JSON array)',
               existing_comment='Languages known (JSON array of strings)',
               existing_nullable=True)
    op.alter_column('candidates', 'preferred_job_role_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Preferred job role',
               existing_nullable=True)
    op.alter_column('candidates', 'preferred_job_category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Preferred job category',
               existing_nullable=True)
    op.alter_column('candidates', 'profile_photo_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Profile photo URL',
               existing_comment='URL to profile photo in S3/Supabase Storage',
               existing_nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email (optional)',
               existing_comment='Email address (optional)',
               existing_nullable=True)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full name',
               existing_comment="Candidate's full name",
               existing_nullable=False)
    op.alter_column('candidates', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary mobile (source of truth)',
               existing_comment='Primary mobile number (source of truth, immutable)',
               existing_nullable=False)
    op.alter_column('candidate_resumes', 'chat_session_id',
               existing_type=sa.UUID(),
               comment='FK to chat session',
               existing_comment='FK to candidate_chat_sessions (if created via bot)',
               existing_nullable=True)
    op.alter_column('candidate_resumes', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='in_progress, completed, invalidated',
               existing_comment='Status: in_progress, completed, invalidated',
               existing_nullable=False)
    op.alter_column('candidate_resumes', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='aivi_bot or pdf_upload',
               existing_comment='How resume was created: aivi_bot, pdf_upload',
               existing_nullable=False)
    op.alter_column('candidate_resumes', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Resume PDF URL',
               existing_comment='URL to resume PDF in S3/Supabase',
               existing_nullable=True)
    op.alter_column('candidate_resumes', 'resume_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured resume data',
               existing_comment='Structured resume data (JSON) for job matching',
               existing_nullable=True)
    op.create_index(op.f('idx_candidate_chat_sessions_candidate_id'), 'candidate_chat_sessions', ['candidate_id'], unique=False)
    op.alter_column('candidate_chat_sessions', 'resume_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to created resume',
               existing_nullable=True)
    op.alter_column('candidate_chat_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Session context (collected_data, step, etc.)',
               existing_comment='Session context (collected_data, step, resume_id, etc.)',
               existing_nullable=True)
    op.alter_column('candidate_chat_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=50),
               comment='active, completed, abandoned',
               existing_comment='Status: active, completed, abandoned',
               existing_nullable=False)
    op.alter_column('candidate_chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               comment='resume_creation, resume_upload, general',
               existing_comment='Type: resume_creation, resume_upload, general',
               existing_nullable=False)
    op.alter_column('candidate_chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Session title',
               existing_comment='Session title (auto-generated)',
               existing_nullable=True)
    op.create_index(op.f('idx_candidate_chat_messages_session_id'), 'candidate_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_candidate_chat_messages_created_at'), 'candidate_chat_messages', ['created_at'], unique=False)
    op.alter_column('candidate_chat_messages', 'message_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional data',
               existing_comment='Additional data (options, validation rules, etc.)',
               existing_nullable=True)
    op.alter_column('candidate_chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               comment='text, buttons, select, etc.',
               existing_comment='Type: text, buttons, select, multi_select, boolean, etc.',
               existing_nullable=False)
    op.alter_column('candidate_chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='Message text',
               existing_comment='Message text content',
               existing_nullable=False)
    # ### end Alembic commands ###
