"""add_composite_indexes_for_chat_sessions

Revision ID: be9084238547
Revises: 008_fallback_questions
Create Date: 2026-02-08 16:49:26.074963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9084238547'
down_revision: Union[str, Sequence[str], None] = '008_fallback_questions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_candidate_chat_sessions_active_resume', 'candidate_chat_sessions', ['candidate_id', 'session_type', 'session_status', 'is_active'], unique=False)
    op.create_index('idx_candidate_chat_sessions_candidate_updated', 'candidate_chat_sessions', ['candidate_id', 'is_active', 'updated_at'], unique=False)
    op.alter_column('candidates', 'profile_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Profile onboarding: basic, complete (distinct from having a resume)',
               existing_comment='Profile status: basic, complete',
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_fallback_questions_lookup'), table_name='fallback_resume_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_fallback_questions_lookup'), 'fallback_resume_questions', ['job_type', 'experience_level', 'display_order'], unique=False)
    op.alter_column('fallback_resume_questions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('fallback_resume_questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.alter_column('candidates', 'profile_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Profile status: basic, complete',
               existing_comment='Profile onboarding: basic, complete (distinct from having a resume)',
               existing_nullable=False)
    op.drop_index('idx_candidate_chat_sessions_candidate_updated', table_name='candidate_chat_sessions')
    op.drop_index('idx_candidate_chat_sessions_active_resume', table_name='candidate_chat_sessions')
    # ### end Alembic commands ###
